version: "3.9"

services:

  game-cat:
    build: .
    container_name: game-cat
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2:1.5b
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull qwen2:1.5b &&
      wait
      "

volumes:
  ollama_data:
